### ISSUE TITLE
Example for Parameters on Patterns page doesn’t compile

### ISSUE THREAD

**Issue by Ivo-Balbaert** [ValeLang/Vale#103]
In the Guide, https://vale.dev/guide/patterns, section: Parameters, the accompanying code snippet does not compile after removing the ... : see error inline (1) below

```
struct Vec3 imm {
  x int;
  y int;
  z int;
}

// Without destructuring:
fn refuel(vec Vec3, len int) Vec3 {
  Vec3(vec.x * len, vec.y * len, vec.z * len)
}

// With destructuring:
fn refueld(Vec3(x, y, z), len int) Vec3 {
  Vec3(x * len, y * len, z * len)
}

fn main() export {
    vec = Vec3(3, 4, 5);
    vecr = vec.refuel(2);
    println(vecr.x + " " + vecr.y + " " + vecr.z); // => 6 8 10
    vecd = vec.refueld(2); // <-- (1) **compile error**
    println(vecd.x + " " + vecd.y + " " + vecd.z); 
}
```
// At line (1):
// internal(-13337) Conflict in determining ordinary rules' runes: 
// InferSolveFailure(Map(ImplicitRune2(FunctionTemplateName2(refueld,0:182),3) -> CoordTemplataType, ImplicitRune2(FunctionTemplateName2(refueld,0:182),4) -> CoordTemplataType, ImplicitRune2(FunctionTemplateName2(refueld,0:182),1) -> CoordTemplataType, ImplicitRune2(FunctionTemplateName2(refueld,0:1

Before this error, I had to change the type of len to int, because of:

parameters.vale:9:8: Couldn't find a suitable function named `*` with args (int, float):
  Vec3(vec.x * len, vec.y * len, vec.z * len)

Rejected candidates:
  builtins/builtinexterns.vale:41:1: *
    Param at index 1 doesn't match: Coord(Share,Float2()) cannot convert to Coord(Share,Int2())
  builtins/builtinexterns.vale:44:1: *
    Param at index 0 doesn't match: Coord(Share,Int2()) cannot convert to Coord(Share,Float2())

Also the functions refuel / refuld must resturn a Vec3.

**Comment by Verdagon** [comment]
Looks like the compiler didn't catch this error because the sample never called the function, so it was never type-checked (which is its own problem). Then, when I made the sample actually call the function, I discovered that _this was never even implemented!_ I totally thought this was done, but there's no trace of the logic that would have made this work.

I'll move this feature to the "future things" section, and add this feature to an upcoming release's to-do list. I'll mark this issue fixed when I deploy the site. Thanks for finding this, Ivo!
