### ISSUE TITLE
Support for DSLs

### ISSUE THREAD

**Issue by sirinath** [ValeLang/Vale#59]
Can support for DSLs be added into the language where things like the following are possible:
- http://groovy-lang.org/dsls.html

Also one can borrow features in Scala which are used to write DSLs.

**Comment by Verdagon** [comment]
I'm not a fan of DSLs, because it's never clear what the line is doing, to a newcomer. Scala and C++ offer this kind of functionality, and its abuse makes it a net negative, when weighed against the potential benefits.

Additionally, DSLs will complicate the parser, because we need to know, for every command, what its precedence is and whether it's a unary operator or a binary operator or something else. This is information that will greatly complicate the parser, and if it's moved to the later stages, will make syntax highlighting inaccurate.

The one concession we made here is infix functions (`aVec cross bVec`), because they don't complicate the parser.
