### ISSUE TITLE
Plans for package manager (like cargo on Rust)

### ISSUE THREAD

**Issue by funatsufumiya** [ValeLang/Vale#591]
I think this disucussion is still early for the current development stage, are there any plans for package manager? (sorry if duplicated issue.)

I read the document about stdlib (for example path), vale would need other (FFI) libraries and build system.

If stdlib is like kind of battery included, many users can use vale as soon, but I think library eco-system is highly needed in the next stage.

**Comment by Verdagon** [comment]
Howdy!

The priority for the last ~half year has been on making a prototype for regions, since that justifies the entire language's existence. Luckily, this prototype is nearing completion (benchmarks this week hopefully, and then I'll spend a few weeks prototyping seamless concurrency to show regions' power) so I can start to turn towards other priorities soon. I think you're right in that packages/ecosystem is up near the top of that priority list.

I want something like cargo, though there's another interesting factor: cross-language support. I want to use Metacall to enable calling into other languages' libraries (something I don't think any language does yet), and I want to figure out the best way to interoperate with other languages nicely. I've heard bazel does pretty well in this regard, but haven't done much investigation.

The first step will probably be to add some flags to the compiler to point to a Rust library (.rlib) directly and ask Metacall (at compile time) what its API looks like, and have valec link it in and figure out the right way to translate / call it. It'll be an interesting quest, that's for sure.

(Also, thanks for sponsoring!)

**Comment by funatsufumiya** [comment]
@Verdagon 
Related to above, CL-CXX-JIT maybe also interesting.
https://github.com/Islam0mar/CL-CXX-JIT

**Comment by funatsufumiya** [comment]
I've seen discussions about embedding Rust in Julia and cbindgen seems to help :)

https://github.com/eqrion/cbindgen

https://discourse.julialang.org/t/ann-embedding-rust-library-in-a-julia-package/15470

**Comment by funatsufumiya** [comment]
I recently think wasm can be true universal FFI as alternative of C header and DLL.
https://extism.org/

**Comment by Verdagon** [comment]
I didn't know about extism, thanks for the tip! The time for inline support is near, as we're close to done fixing the tech debt from generics and regions, so the timing is good.

Extism sounds like it could help us run arbitrary languages' code in a sandbox, which we indeed need for the "fearless FFI" feature. I'm curious how this compares to something like Metacall.

Before that, the first step will probably be interop with Rust, as they've got a nice ecosystem that Vale could benefit from. Once that's sorted, I'll take a close look at extism and Metacall (and others?) and figure out a nice direction.

**Comment by funatsufumiya** [comment]
@Verdagon 
Metacall provides the interface for interoperation using C API, while extism is using WASM.
I think interface protocol is anything OK if it's common and maintenable, but the problem is writing interface itself by programmer would be a burden. So how easily automatically generating it would be important, like cbindgen of Rust.

**Comment by paulocoghi** [comment]
Leaving aside the differences in complexity, wouldn't WASM provide reduced performance compared to "native" calls from other strategies based on C, like Metacall does?

In other words, would't be better to use Metacall instead of WASM, to guarantee better performance?

**Comment by paulocoghi** [comment]
To give better context, I bring the excellent work of Frank Denis.

In January of this year, he made an [update](https://00f.net/2023/01/04/webassembly-benchmark-2023/) about the performance of numerous webassembly runtimes, both against javascript runtimes, as well as native code.

On the native side, to support my claims of wasm being slower, Frank's tests results show that it is about 2.32 times slower (which is not all that bad, but it is still slower). But there is a catch _(see below the graph)_.

![wasm-vs-native](https://github.com/ValeLang/Vale/assets/378397/44e177c0-524e-48c3-80d5-6f243cafbc96)

**The encryption use case**

But this average of 2.32x is ignoring some encryption scenarios, like AES, where wasm were 80x times slower.

For most use cases for wasm, this isn't a concern. But for a general purpose language, tho, it surely is.
