### ISSUE TITLE
Non-Owning References

### ISSUE THREAD

**Issue by sirinath** [ValeLang/Vale#65]
When there is a Non-Owning References ensure:
- Compile-time RC to deallocate
- Non-Owning References are immutable while the Owning References are mutable

This way we can avoid the runtime exception, possible data race issues and additional plumbing.

Ideally, all possible errors should be handled at compile time with no runtime errors.

**Comment by Verdagon** [comment]
By compile-time RC, do you mean like what Lobster does? They came up with some pretty brilliant stuff, and there's already plans to incorporate as much of their innovations as we can. It's not directly applicable since they're built on RC and we're built on single ownership, but perhaps some of the basic principles can be carried over.

Mutable non-owning references and immutable non-owning references sounds like Rust's borrow checker. The borrow checker's costs (learning curve, readability, architectural damage) are not worth the costs, especially considering hybrid-generational memory can get near-or-equal speed without any additional complexity.

Even the borrow checker doesn't catch invalid accesses at compile time. The borrow checker often forces you to work around it, with things like Rc<RefCell<T>> and generational indices, both which have run-time checks and halts. It's an improvement over C, but we can do better!

Also, we already have non-owning references, called constraint references, so I'll close this. We can open a different issue specifically for discussing the merits and costs of adding a borrow checker.

**Comment by sirinath** [comment]
My main issue here is that under the current scheme a runtime exception can be generated if the reference is freed. Whatever approach needed to try to avoid the exception. This can mean a scheme to delay releasing such memory or some other scheme than currently used which does not result in a runtime exception.

**Comment by Verdagon** [comment]
Check out the draft of HGM at https://vale.dev/blog/hybrid-generational-memory-part-1, it explains a little more of our direction and why we're not interested in adding a borrow checker.

**Comment by sirinath** [comment]
I don't care about if there is a borrow checker or not. What I care about is the possibility of runtime exceptions when using Non-Owning References. Anyways to prevent runtime exceptions are welcome.

**Comment by Verdagon** [comment]
Got it, thanks for clarifying!

Without the borrow checker, the only other approaches are reference counting, which has a lot of performance costs, and garbage collection, which has almost as much performance costs plus nondeterministic pauses.

HGM is a bit more promising, it looks like it will have less costs than both of them, but we will see.

**Comment by sirinath** [comment]
Can the lifetime be determined through static analysis, without a fully-fledged borrow checker, this can be done? The question needs to be answered in checking is does this reference outlive the other references pointing to the object.
