### ISSUE TITLE
Couldn't find a suitable function named Array with args (int, ??

### ISSUE THREAD

**Issue by Ivo-Balbaert** [ValeLang/Vale#93]
If the previous array example is changed to:

arr = Array(4, {_ * 5}); // [0, 5, 10, 15] 

The compiler says get: Couldn't find a suitable function named Array with args (int, ??main<>().?0:36):

**Comment by Verdagon** [comment]
I see what happened here. This was something I optimistically updated in the documentation, but got later cut from the 0.1 scope. Lesson learned: I should update the documentation in the same pull request as the code fix, so that they go in together or not at all.

Just updated the site to use `MakeArray(4, {_ * 5});` instead, will mark this fixed when the site gets pushed next.

**Comment by Ivo-Balbaert** [comment]
Thanks!

**Comment by Ivo-Balbaert** [comment]
This syntax also works:  arr = Arr<imm>(4, {_ * 5});  or arr = Arr<mut>(4, {_ * 5});

**Comment by Verdagon** [comment]
Fixed in v0.1.1. Thanks Ivo!
